import { z } from "zod";

// Single source of truth for every D2L Valence route this server knows how to call.
// Populated from openspec/changes/add-d2l-route-catalog/specs/d2l-route-catalog/catalog.md —
// that file documents the research (path/query params, response envelope, doc source,
// confidence) behind every entry below; keep the two in sync when either changes.
//
// `pathTemplate` always includes `{orgUnitId}` literally for course-scoped routes, but
// `pathParams` never does — orgUnitId is resolved from the caller's courseId, never accepted
// as a direct parameter (see resolveD2lPath in d2l.ts and Decision 3 in design.md). Every other
// `{placeholder}` in pathTemplate must have a matching key in pathParams.

export type D2lProduct = "le" | "lp";
export type D2lScope = "course" | "user" | "global";
// "binary" routes return raw file bytes, not JSON — callers must not attempt to parse the body.
export type D2lPagination = "none" | "objectList" | "bookmark" | "binary";

export interface D2lRouteDescriptor {
  operation: string;
  product: D2lProduct;
  method: "GET";
  pathTemplate: string;
  scope: D2lScope;
  pathParams: z.ZodObject<z.ZodRawShape>;
  queryParams?: z.ZodObject<z.ZodRawShape>;
  pagination: D2lPagination;
  category: string;
  description: string;
  // Most rows back at most one curated tool; a couple (le.quizzes.attempts,
  // le.surveys.attempts) back two — the existing own-scoped tool and the new
  // class-wide one, both hitting the same underlying route.
  curatedTools?: string[];
}

// --- shared param fragments -------------------------------------------------

const id = () => z.coerce.number().int();
const noParams = z.object({});
const userRoleQuery = z.object({ userId: id().optional(), roleId: id().optional() });
const userIdOptionalQuery = z.object({ userId: id().optional() });
const bookmarkQuery = z.object({ bookmark: z.string().optional() });
const pagedQuery = z.object({ pageSize: id().optional(), pageNumber: id().optional() });
const orgUnitIdsCsvQuery = (extra?: z.ZodRawShape) =>
  z.object({ orgUnitIdsCSV: z.string(), ...(extra ?? {}) });

function route(entry: D2lRouteDescriptor): D2lRouteDescriptor {
  return entry;
}

// --- Assessment & Rubrics ---------------------------------------------------

const assessmentRubrics: D2lRouteDescriptor[] = [
  route({
    operation: "le.assessment.get",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/assessment",
    scope: "course",
    pathParams: noParams,
    queryParams: z.object({
      assessmentType: z.string(),
      objectType: z.string(),
      objectId: id(),
      rubricId: id(),
      userId: id(),
    }),
    pagination: "none",
    category: "assessment-rubrics",
    description: "Retrieve a rubric-based assessment (evaluation outcome) for a specific object and user in an org unit.",
  }),
  route({
    operation: "le.rubrics.list",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/rubrics/",
    scope: "course",
    pathParams: noParams,
    queryParams: z.object({ objectType: z.string(), objectId: id() }),
    pagination: "none",
    category: "assessment-rubrics",
    description: "Retrieve all rubrics that apply to a specified object in an org unit.",
    curatedTools: ["get_rubrics"],
  }),
  route({
    operation: "le.rubrics.get",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/rubrics/{rubricId}",
    scope: "course",
    pathParams: z.object({ rubricId: id() }),
    pagination: "none",
    category: "assessment-rubrics",
    description: "Retrieve a single rubric by ID.",
    curatedTools: ["get_rubrics"],
  }),
];

// --- Calendar & Events (course-scoped) --------------------------------------

const calendar: D2lRouteDescriptor[] = [
  route({
    operation: "le.calendar.eventGet",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/calendar/event/{eventId}",
    scope: "course",
    pathParams: z.object({ eventId: id() }),
    pagination: "none",
    category: "calendar",
    description: "Retrieve a calendar event from a particular org unit.",
  }),
  route({
    operation: "le.calendar.eventAccess",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/calendar/event/{eventId}/access/",
    scope: "course",
    pathParams: z.object({ eventId: id() }),
    queryParams: userRoleQuery.merge(bookmarkQuery),
    pagination: "bookmark",
    category: "calendar",
    description: "Retrieve the list of users with access to a specified calendar event.",
  }),
  route({
    operation: "le.calendar.eventOccurrences",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/calendar/event/{eventId}/occurrences",
    scope: "course",
    pathParams: z.object({ eventId: id() }),
    pagination: "none",
    category: "calendar",
    description: "Retrieve a calendar event's occurrences.",
  }),
  route({
    operation: "le.calendar.list",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/calendar/events/",
    scope: "course",
    pathParams: noParams,
    queryParams: z.object({ associatedEventsOnly: z.coerce.boolean().optional() }),
    pagination: "none",
    category: "calendar",
    description: "Retrieve all calendar events for the calling user within the provided org unit context.",
    curatedTools: ["get_calendar_events"],
  }),
  route({
    operation: "le.calendar.itemCountForUser",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/calendar/events/{userId}/itemCount",
    scope: "course",
    pathParams: z.object({ userId: id() }),
    queryParams: z.object({
      association: z.string().optional(),
      eventType: z.string().optional(),
      startDateTime: z.string(),
      endDateTime: z.string(),
    }),
    pagination: "none",
    category: "calendar",
    description: "Retrieve a filtered count of a user's calendar events within one org unit.",
  }),
  route({
    operation: "le.calendar.myEvents",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/calendar/events/myEvents/",
    scope: "course",
    pathParams: noParams,
    queryParams: z.object({
      association: z.string().optional(),
      eventType: z.string().optional(),
      startDateTime: z.string().optional(),
      endDateTime: z.string().optional(),
    }),
    pagination: "objectList",
    category: "calendar",
    description: "Retrieve the calling user's events for a particular org unit.",
  }),
  route({
    operation: "le.calendar.myEventsItemCount",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/calendar/events/myEvents/itemCount",
    scope: "course",
    pathParams: noParams,
    queryParams: z.object({
      association: z.string().optional(),
      eventType: z.string().optional(),
      startDateTime: z.string().optional(),
      endDateTime: z.string().optional(),
    }),
    pagination: "none",
    category: "calendar",
    description: "Retrieve a count of the calling user's calendar events within the org unit.",
  }),
  route({
    operation: "le.calendar.occurrences",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/calendar/events/occurrences/",
    scope: "course",
    pathParams: noParams,
    queryParams: z.object({
      association: z.string().optional(),
      eventType: z.string().optional(),
      startDateTime: z.string(),
      endDateTime: z.string(),
    }),
    pagination: "objectList",
    category: "calendar",
    description: "Retrieve all calendar event occurrences for the calling user within the org unit, in a required time window.",
  }),
  route({
    operation: "le.calendar.orgUnits",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/calendar/events/orgunits/",
    scope: "course",
    pathParams: noParams,
    queryParams: z.object({ orgUnitIdsCSV: z.string(), startDateTime: z.string(), endDateTime: z.string() }).merge(bookmarkQuery),
    pagination: "bookmark",
    category: "calendar",
    description: "Retrieve all calendar events for the calling user across a provided set of org units.",
  }),
  route({
    operation: "le.calendar.userEvents",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/calendar/events/user/",
    scope: "course",
    pathParams: noParams,
    queryParams: z.object({ userId: id(), startDateTime: z.string(), endDateTime: z.string() }).merge(bookmarkQuery),
    pagination: "bookmark",
    category: "calendar",
    description:
      "Retrieve all calendar events for a specified user's explicit enrollments within the organization containing the given org unit. Requires calendar-management permission in that org unit.",
  }),
];

// --- Checklists --------------------------------------------------------------

const checklists: D2lRouteDescriptor[] = [
  route({
    operation: "le.checklists.list",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/checklists/",
    scope: "course",
    pathParams: noParams,
    pagination: "objectList",
    category: "checklists",
    description: "Retrieve all checklists belonging to an org unit.",
  }),
  route({
    operation: "le.checklists.get",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/checklists/{checklistId}",
    scope: "course",
    pathParams: z.object({ checklistId: id() }),
    pagination: "none",
    category: "checklists",
    description: "Retrieve a specific checklist belonging to an org unit.",
  }),
  route({
    operation: "le.checklists.categoriesList",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/checklists/{checklistId}/categories/",
    scope: "course",
    pathParams: z.object({ checklistId: id() }),
    pagination: "objectList",
    category: "checklists",
    description: "Retrieve all categories belonging to a checklist.",
  }),
  route({
    operation: "le.checklists.categoryGet",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/checklists/{checklistId}/categories/{categoryId}",
    scope: "course",
    pathParams: z.object({ checklistId: id(), categoryId: id() }),
    pagination: "none",
    category: "checklists",
    description: "Retrieve a specific category belonging to a checklist.",
  }),
  route({
    operation: "le.checklists.itemsList",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/checklists/{checklistId}/items/",
    scope: "course",
    pathParams: z.object({ checklistId: id() }),
    pagination: "objectList",
    category: "checklists",
    description: "Retrieve all items belonging to a checklist.",
  }),
  route({
    operation: "le.checklists.itemGet",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/checklists/{checklistId}/items/{checklistItemId}",
    scope: "course",
    pathParams: z.object({ checklistId: id(), checklistItemId: id() }),
    pagination: "none",
    category: "checklists",
    description: "Retrieve a specific item belonging to a checklist.",
  }),
];

// --- Content & Modules ---------------------------------------------------------

const content: D2lRouteDescriptor[] = [
  route({
    operation: "le.content.bookmarks",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/content/bookmarks",
    scope: "course",
    pathParams: noParams,
    pagination: "none",
    category: "content",
    description: "Retrieve a list of topics that have been bookmarked by the calling user.",
  }),
  route({
    operation: "le.content.completionsList",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/content/completions/",
    scope: "course",
    pathParams: noParams,
    queryParams: z.object({ userIdsCSV: z.string(), ignoreInvalid: z.coerce.boolean().optional() }),
    pagination: "none",
    category: "content",
    description:
      "Retrieve the count of completed and required content topics in an org unit for each user in a supplied CSV list.",
  }),
  route({
    operation: "le.content.completionsMyCount",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/content/completions/mycount/",
    scope: "course",
    pathParams: noParams,
    queryParams: z.object({ level: z.string() }),
    pagination: "objectList",
    category: "content",
    description: "Retrieve the aggregate count of completed and required content topics in an org unit for the calling user.",
  }),
  route({
    operation: "le.content.moduleGet",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/content/modules/{moduleId}",
    scope: "course",
    pathParams: z.object({ moduleId: id() }),
    pagination: "none",
    category: "content",
    description: "Retrieve a specific content module for an org unit.",
  }),
  route({
    operation: "le.content.moduleAccess",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/content/modules/{moduleId}/access/",
    scope: "course",
    pathParams: z.object({ moduleId: id() }),
    queryParams: userRoleQuery,
    pagination: "objectList",
    category: "content",
    description: "Retrieve the list of users with access to a specified module.",
  }),
  route({
    operation: "le.content.moduleStructure",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/content/modules/{moduleId}/structure/",
    scope: "course",
    pathParams: z.object({ moduleId: id() }),
    pagination: "none",
    category: "content",
    description: "Retrieve the structure (child modules/topics) for a specific module.",
  }),
  route({
    operation: "le.content.myItems",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/content/myItems/",
    scope: "course",
    pathParams: noParams,
    queryParams: z.object({ completion: z.string().optional(), startDateTime: z.string().optional(), endDateTime: z.string().optional() }),
    pagination: "objectList",
    category: "content",
    description: "Retrieve the calling user's scheduled content items for a particular org unit.",
  }),
  route({
    operation: "le.content.myItemsDue",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/content/myItems/due/",
    scope: "course",
    pathParams: noParams,
    queryParams: z.object({ completion: z.string().optional(), startDateTime: z.string().optional(), endDateTime: z.string().optional() }),
    pagination: "objectList",
    category: "content",
    description: "Retrieve the calling user's scheduled items still due for a particular org unit.",
  }),
  route({
    operation: "le.content.myItemsDueCount",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/content/myItems/due/itemCount",
    scope: "course",
    pathParams: noParams,
    queryParams: z.object({ completion: z.string().optional(), startDateTime: z.string().optional(), endDateTime: z.string().optional() }),
    pagination: "none",
    category: "content",
    description: "Retrieve the quantity of the calling user's scheduled items still due for a particular org unit.",
  }),
  route({
    operation: "le.content.myItemsCount",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/content/myItems/itemCount",
    scope: "course",
    pathParams: noParams,
    queryParams: z.object({ completion: z.string().optional(), startDateTime: z.string().optional(), endDateTime: z.string().optional() }),
    pagination: "none",
    category: "content",
    description: "Retrieve the quantity of the calling user's scheduled items for a particular org unit.",
  }),
  route({
    operation: "le.content.pacing",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/content/pacing",
    scope: "course",
    pathParams: noParams,
    pagination: "none",
    category: "content",
    description: "Retrieve pacing dates (course/semester start & end) for content.",
  }),
  route({
    operation: "le.content.recent",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/content/recent",
    scope: "course",
    pathParams: noParams,
    pagination: "none",
    category: "content",
    description: "Retrieve a list of the most recently visited topics for the calling user.",
  }),
  route({
    operation: "le.content.root",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/content/root/",
    scope: "course",
    pathParams: noParams,
    pagination: "none",
    category: "content",
    description: "Retrieve the root module(s) for an org unit.",
  }),
  route({
    operation: "le.content.toc",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/content/toc",
    scope: "course",
    pathParams: noParams,
    queryParams: z.object({
      ignoreDateRestrictions: z.coerce.boolean().optional(),
      ignoreModuleDateRestrictions: z.coerce.boolean().optional(),
      userId: id().optional(),
      moduleId: id().optional(),
      title: z.string().optional(),
    }),
    pagination: "none",
    category: "content",
    description: "Retrieve the table of course content for an org unit.",
    curatedTools: ["get_course_content"],
  }),
  route({
    operation: "le.content.topicGet",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/content/topics/{topicId}",
    scope: "course",
    pathParams: z.object({ topicId: id() }),
    pagination: "none",
    category: "content",
    description: "Retrieve a specific content topic for an org unit.",
    curatedTools: ["get_content_topic"],
  }),
  route({
    operation: "le.content.topicAccess",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/content/topics/{topicId}/access/",
    scope: "course",
    pathParams: z.object({ topicId: id() }),
    queryParams: userRoleQuery,
    pagination: "objectList",
    category: "content",
    description: "Retrieve the list of users with access to a specified content topic.",
  }),
  route({
    operation: "le.content.topicCaptions",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/content/topics/{topicId}/captions",
    scope: "course",
    pathParams: z.object({ topicId: id() }),
    pagination: "objectList",
    category: "content",
    description: "Retrieve metadata for all caption files associated with an audio/video content topic.",
  }),
  route({
    operation: "le.content.topicCompletionsList",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/content/topics/{topicId}/completions/",
    scope: "course",
    pathParams: z.object({ topicId: id() }),
    queryParams: z.object({
      userId: id().optional(),
      isAscendingSort: z.coerce.boolean().optional(),
      userBookmark: id().optional(),
      pageSize: id().optional(),
    }),
    pagination: "objectList",
    category: "content",
    description: "Retrieve a list of content topic completions for a topic, for users the caller has access to.",
  }),
  route({
    operation: "le.content.topicCompletionForUser",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/content/topics/{topicId}/completions/users/{userId}",
    scope: "course",
    pathParams: z.object({ topicId: id(), userId: id() }),
    pagination: "none",
    category: "content",
    description: "Retrieve a content topic completion for a topic, for a particular user.",
  }),
  route({
    operation: "le.content.topicFile",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/content/topics/{topicId}/file",
    scope: "course",
    pathParams: z.object({ topicId: id() }),
    queryParams: z.object({ stream: z.coerce.boolean().optional() }),
    pagination: "binary",
    category: "content",
    description: "Retrieve the underlying file for a file-type content topic.",
  }),
  route({
    operation: "le.content.userProgress",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/content/userprogress/",
    scope: "course",
    pathParams: noParams,
    queryParams: z.object({ userId: id().optional(), objectId: id().optional(), pageSize: id().optional() }),
    pagination: "objectList",
    category: "content",
    description: "Retrieve user progress items in an org unit for specific users or content topics (only users with recorded progress are returned).",
  }),
  route({
    operation: "le.content.topicProgress",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/content/userprogress/{topicId}",
    scope: "course",
    pathParams: z.object({ topicId: id() }),
    queryParams: userIdOptionalQuery,
    pagination: "none",
    category: "content",
    description: "Retrieve one user's progress within an org unit for a particular content topic (includes users at the default/no-progress state, unlike le.content.userProgress's list).",
  }),
];

// --- Competencies --------------------------------------------------------------

const competencies: D2lRouteDescriptor[] = [
  route({
    operation: "le.competencies.structure",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/competencies/structure",
    scope: "course",
    pathParams: noParams,
    queryParams: z.object({
      parentObjectId: id().optional(),
      depth: id().optional(),
      pageSize: id().optional(),
      bookmark: id().optional(),
      forUserId: id().optional(),
    }),
    pagination: "objectList",
    category: "competencies",
    description:
      "Retrieve the structure of course competencies and objectives visible to the calling user (a graph with a virtual, non-returned root node).",
  }),
];

// --- Discussions & Forums --------------------------------------------------------------

const discussions: D2lRouteDescriptor[] = [
  route({
    operation: "le.discussions.deletedList",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/discussions/deleted",
    scope: "course",
    pathParams: noParams,
    pagination: "none",
    category: "discussions",
    description: "Retrieve deleted discussion forums and topics for an org unit.",
  }),
  route({
    operation: "le.discussions.forumsList",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/discussions/forums/",
    scope: "course",
    pathParams: noParams,
    pagination: "none",
    category: "discussions",
    description: "Retrieve a list of all discussion forums for an org unit.",
    curatedTools: ["get_discussion_forums"],
  }),
  route({
    operation: "le.discussions.forumGet",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/discussions/forums/{forumId}",
    scope: "course",
    pathParams: z.object({ forumId: id() }),
    pagination: "none",
    category: "discussions",
    description: "Retrieve a particular discussion forum for an org unit.",
  }),
  route({
    operation: "le.discussions.forumAccess",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/discussions/forums/{forumId}/access/",
    scope: "course",
    pathParams: z.object({ forumId: id() }),
    queryParams: userRoleQuery.merge(bookmarkQuery),
    pagination: "objectList",
    category: "discussions",
    description: "Retrieve a list of users with access to a specified forum.",
  }),
  route({
    operation: "le.discussions.forumStatistics",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/discussions/forums/{forumId}/statistics",
    scope: "course",
    pathParams: z.object({ forumId: id() }),
    pagination: "none",
    category: "discussions",
    description: "Retrieve discussion statistics for a specific forum within an org unit.",
  }),
  route({
    operation: "le.discussions.topicsList",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/discussions/forums/{forumId}/topics/",
    scope: "course",
    pathParams: z.object({ forumId: id() }),
    pagination: "none",
    category: "discussions",
    description: "Retrieve topics from the provided discussion forum in an org unit.",
    curatedTools: ["get_discussion_topics"],
  }),
  route({
    operation: "le.discussions.topicGet",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/discussions/forums/{forumId}/topics/{topicId}",
    scope: "course",
    pathParams: z.object({ forumId: id(), topicId: id() }),
    pagination: "none",
    category: "discussions",
    description: "Retrieve a particular topic from the provided discussion forum in an org unit.",
  }),
  route({
    operation: "le.discussions.topicAccess",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/discussions/forums/{forumId}/topics/{topicId}/access/",
    scope: "course",
    pathParams: z.object({ forumId: id(), topicId: id() }),
    queryParams: userRoleQuery,
    pagination: "objectList",
    category: "discussions",
    description: "Retrieve a list of users with access to a specified topic within a forum.",
  }),
  route({
    operation: "le.discussions.topicExemption",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/discussions/forums/{forumId}/topics/{topicId}/exemption",
    scope: "course",
    pathParams: z.object({ forumId: id(), topicId: id() }),
    pagination: "none",
    category: "discussions",
    description: "Retrieve the list of users currently exempted from a discussion topic.",
  }),
  route({
    operation: "le.discussions.topicGroupRestrictions",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/discussions/forums/{forumId}/topics/{topicId}/groupRestrictions/",
    scope: "course",
    pathParams: z.object({ forumId: id(), topicId: id() }),
    pagination: "none",
    category: "discussions",
    description: "Retrieve the group restrictions for a discussion forum topic.",
  }),
  route({
    operation: "le.discussions.postsList",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/discussions/forums/{forumId}/topics/{topicId}/posts/",
    scope: "course",
    pathParams: z.object({ forumId: id(), topicId: id() }),
    queryParams: z.object({
      pageSize: id().optional(),
      pageNumber: id().optional(),
      threadsOnly: z.coerce.boolean().optional(),
      threadId: id().optional(),
      sort: z.string().optional(),
    }),
    pagination: "none",
    category: "discussions",
    description: "Retrieve all posts (including threads) in a discussion forum topic.",
    curatedTools: ["get_discussion_posts"],
  }),
  route({
    operation: "le.discussions.postGet",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/discussions/forums/{forumId}/topics/{topicId}/posts/{postId}",
    scope: "course",
    pathParams: z.object({ forumId: id(), topicId: id(), postId: id() }),
    pagination: "none",
    category: "discussions",
    description: "Retrieve a particular post in a discussion forum topic.",
  }),
  route({
    operation: "le.discussions.postApproval",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/discussions/forums/{forumId}/topics/{topicId}/posts/{postId}/Approval",
    scope: "course",
    pathParams: z.object({ forumId: id(), topicId: id(), postId: id() }),
    pagination: "none",
    category: "discussions",
    description: "Retrieve the approval status for a particular post.",
  }),
  route({
    operation: "le.discussions.postFlag",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/discussions/forums/{forumId}/topics/{topicId}/posts/{postId}/Flag",
    scope: "course",
    pathParams: z.object({ forumId: id(), topicId: id(), postId: id() }),
    pagination: "none",
    category: "discussions",
    description: "Retrieve the flagged status for a particular post.",
  }),
  route({
    operation: "le.discussions.postRating",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/discussions/forums/{forumId}/topics/{topicId}/posts/{postId}/Rating",
    scope: "course",
    pathParams: z.object({ forumId: id(), topicId: id(), postId: id() }),
    pagination: "none",
    category: "discussions",
    description: "Retrieve the rating data for a particular post.",
  }),
  route({
    operation: "le.discussions.postMyRating",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/discussions/forums/{forumId}/topics/{topicId}/posts/{postId}/Rating/MyRating",
    scope: "course",
    pathParams: z.object({ forumId: id(), topicId: id(), postId: id() }),
    pagination: "none",
    category: "discussions",
    description: "Retrieve the current user's rating data for a particular post.",
  }),
  route({
    operation: "le.discussions.postReadStatus",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/discussions/forums/{forumId}/topics/{topicId}/posts/{postId}/ReadStatus",
    scope: "course",
    pathParams: z.object({ forumId: id(), topicId: id(), postId: id() }),
    pagination: "none",
    category: "discussions",
    description: "Retrieve the current read status for a particular post.",
  }),
  route({
    operation: "le.discussions.postVotes",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/discussions/forums/{forumId}/topics/{topicId}/posts/{postId}/Votes",
    scope: "course",
    pathParams: z.object({ forumId: id(), topicId: id(), postId: id() }),
    pagination: "none",
    category: "discussions",
    description: "Retrieve all the vote data for a particular post.",
  }),
  route({
    operation: "le.discussions.postMyVote",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/discussions/forums/{forumId}/topics/{topicId}/posts/{postId}/Votes/MyVote",
    scope: "course",
    pathParams: z.object({ forumId: id(), topicId: id(), postId: id() }),
    pagination: "none",
    category: "discussions",
    description: "Retrieve the current user's vote data for a particular post.",
  }),
  route({
    operation: "le.discussions.postAttachment",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/discussions/forums/{forumId}/topics/{topicId}/posts/{postId}/attachments/{fileId}",
    scope: "course",
    pathParams: z.object({ forumId: id(), topicId: id(), postId: id(), fileId: id() }),
    pagination: "binary",
    category: "discussions",
    description: "Retrieve a specific file attachment from a discussion forum post.",
  }),
  route({
    operation: "le.discussions.topicStatistics",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/discussions/forums/{forumId}/topics/{topicId}/statistics",
    scope: "course",
    pathParams: z.object({ forumId: id(), topicId: id() }),
    pagination: "none",
    category: "discussions",
    description: "Retrieve discussion statistics for a specific topic within a forum.",
  }),
  route({
    operation: "le.discussions.topicUserStatistics",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/discussions/forums/{forumId}/topics/{topicId}/userstatistics",
    scope: "course",
    pathParams: z.object({ forumId: id(), topicId: id() }),
    queryParams: pagedQuery,
    pagination: "none",
    category: "discussions",
    description: "Retrieve per-user discussion statistics for a specific topic within a forum, sorted by last name ascending.",
  }),
  route({
    operation: "le.discussions.forumTopicStatistics",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/discussions/forumtopicstatistics",
    scope: "course",
    pathParams: noParams,
    queryParams: pagedQuery,
    pagination: "none",
    category: "discussions",
    description: "Retrieve discussion statistics for an org unit, broken down by forum and topic.",
  }),
  route({
    operation: "le.discussions.statistics",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/discussions/statistics",
    scope: "course",
    pathParams: noParams,
    pagination: "none",
    category: "discussions",
    description: "Retrieve overall discussion statistics for an org unit.",
  }),
  route({
    operation: "le.discussions.userStatistics",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/discussions/userstatistics",
    scope: "course",
    pathParams: noParams,
    queryParams: pagedQuery,
    pagination: "none",
    category: "discussions",
    description: "Retrieve per-user discussion statistics for an org unit, sorted by last name ascending.",
  }),
];

// --- Dropbox & Assignments --------------------------------------------------------------

const dropbox: D2lRouteDescriptor[] = [
  route({
    operation: "le.dropbox.categoriesList",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/dropbox/categories/",
    scope: "course",
    pathParams: noParams,
    pagination: "none",
    category: "dropbox",
    description: "Retrieve all dropbox folder categories for an org unit.",
  }),
  route({
    operation: "le.dropbox.categoryGet",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/dropbox/categories/{categoryId}",
    scope: "course",
    pathParams: z.object({ categoryId: id() }),
    pagination: "none",
    category: "dropbox",
    description: "Retrieve a specific dropbox folder category, including the folders that belong to it.",
  }),
  route({
    operation: "le.dropbox.foldersList",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/dropbox/folders/",
    scope: "course",
    pathParams: noParams,
    queryParams: z.object({ onlyCurrentStudentsAndGroups: z.coerce.boolean().optional() }),
    pagination: "none",
    category: "dropbox",
    description: "Retrieve all dropbox folders for an org unit.",
    curatedTools: ["get_assignments"],
  }),
  route({
    operation: "le.dropbox.folderGet",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/dropbox/folders/{folderId}",
    scope: "course",
    pathParams: z.object({ folderId: id() }),
    pagination: "none",
    category: "dropbox",
    description: "Retrieve a specific dropbox folder.",
  }),
  route({
    operation: "le.dropbox.folderAccess",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/dropbox/folders/{folderId}/access/",
    scope: "course",
    pathParams: z.object({ folderId: id() }),
    queryParams: userRoleQuery.merge(bookmarkQuery),
    pagination: "bookmark",
    category: "dropbox",
    description: "Retrieve the list of users with access to a specified dropbox folder.",
  }),
  route({
    operation: "le.dropbox.folderAttachment",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/dropbox/folders/{folderId}/attachments/{fileId}",
    scope: "course",
    pathParams: z.object({ folderId: id(), fileId: id() }),
    pagination: "binary",
    category: "dropbox",
    description: "Retrieve a file attachment from a specific dropbox folder (not for link attachments).",
  }),
  route({
    operation: "le.dropbox.feedbackGet",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/dropbox/folders/{folderId}/feedback/{entityType}/{entityId}",
    scope: "course",
    pathParams: z.object({ folderId: id(), entityType: z.enum(["user", "group"]), entityId: id() }),
    pagination: "none",
    category: "dropbox",
    description: "Retrieve the feedback entry from a dropbox folder for a given entity (user or group).",
    curatedTools: ["get_my_dropbox_submission"],
  }),
  route({
    operation: "le.dropbox.feedbackAttachment",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/dropbox/folders/{folderId}/feedback/{entityType}/{entityId}/attachments/{fileId}",
    scope: "course",
    pathParams: z.object({ folderId: id(), entityType: z.enum(["user", "group"]), entityId: id(), fileId: id() }),
    pagination: "binary",
    category: "dropbox",
    description: "Retrieve a feedback entry's file attachment.",
  }),
  route({
    operation: "le.dropbox.feedbackLink",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/dropbox/folders/{folderId}/feedback/{entityType}/{entityId}/links/{linkId}",
    scope: "course",
    pathParams: z.object({ folderId: id(), entityType: z.enum(["user", "group"]), entityId: id(), linkId: id() }),
    pagination: "binary",
    category: "dropbox",
    description: "Retrieve a feedback entry's linked media-content attachment (audio/video recorded feedback only).",
  }),
  route({
    operation: "le.dropbox.groupSubmissionDownload",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/dropbox/folders/{folderId}/group-submissions/{groupId}/download",
    scope: "course",
    pathParams: z.object({ folderId: id(), groupId: id() }),
    pagination: "binary",
    category: "dropbox",
    description: "Download a zip of all files submitted by users in a group for a dropbox folder.",
  }),
  route({
    operation: "le.dropbox.specialAccessList",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/dropbox/folders/{folderId}/specialaccess/",
    scope: "course",
    pathParams: z.object({ folderId: id() }),
    pagination: "bookmark",
    category: "dropbox",
    description: "Retrieve special access rules for users in a specified dropbox folder.",
  }),
  route({
    operation: "le.dropbox.specialAccessGet",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/dropbox/folders/{folderId}/specialaccess/{userId}",
    scope: "course",
    pathParams: z.object({ folderId: id(), userId: id() }),
    pagination: "none",
    category: "dropbox",
    description: "Retrieve the special access rule for a specific user in a dropbox folder.",
  }),
  route({
    operation: "le.dropbox.submissionsPaged",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/dropbox/folders/{folderId}/submissions/paged/",
    scope: "course",
    pathParams: z.object({ folderId: id() }),
    queryParams: z.object({ activeOnly: z.coerce.boolean().optional() }).merge(bookmarkQuery),
    pagination: "bookmark",
    category: "dropbox",
    description:
      "Retrieve a page of submissions (with feedback if present) for a specific dropbox folder. D2L's recommended route over the unpaged submissions/ route.",
    curatedTools: ["get_dropbox_submissions"],
  }),
  route({
    operation: "le.dropbox.submissionsAll",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/dropbox/folders/{folderId}/submissions/",
    scope: "course",
    pathParams: z.object({ folderId: id() }),
    queryParams: z.object({ activeOnly: z.coerce.boolean().optional() }),
    pagination: "none",
    category: "dropbox",
    description:
      "Retrieve ALL submissions for a dropbox folder, unpaged. D2L's docs actively discourage this for folders with many submissions — prefer le.dropbox.submissionsPaged.",
  }),
  route({
    operation: "le.dropbox.submissionFile",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/dropbox/folders/{folderId}/submissions/{submissionId}/files/{fileId}",
    scope: "course",
    pathParams: z.object({ folderId: id(), submissionId: id(), fileId: id() }),
    pagination: "binary",
    category: "dropbox",
    description: "Retrieve one file from a submission in a dropbox folder.",
  }),
  route({
    operation: "le.dropbox.submissionDownload",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/dropbox/folders/{folderId}/submissions/{userId}/download",
    scope: "course",
    pathParams: z.object({ folderId: id(), userId: id() }),
    pagination: "binary",
    category: "dropbox",
    description: "Download a zip of all files submitted by a user for a dropbox folder.",
  }),
  route({
    operation: "le.dropbox.groupSubmissionGet",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/dropbox/folders/{folderId}/submissions/group/{groupId}",
    scope: "course",
    pathParams: z.object({ folderId: id(), groupId: id() }),
    queryParams: z.object({ ignoreFeedback: z.coerce.boolean().optional() }),
    pagination: "none",
    category: "dropbox",
    description: "Retrieve all submissions made by a specific group in a dropbox folder.",
  }),
  route({
    operation: "le.dropbox.mySubmissions",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/dropbox/folders/{folderId}/submissions/mysubmissions/",
    scope: "course",
    pathParams: z.object({ folderId: id() }),
    pagination: "none",
    category: "dropbox",
    description: "Retrieve all submissions made by the current user to a dropbox folder.",
    curatedTools: ["get_my_dropbox_submission"],
  }),
  route({
    operation: "le.dropbox.submissionForUser",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/dropbox/folders/{folderId}/submissions/user/{userId}",
    scope: "course",
    pathParams: z.object({ folderId: id(), userId: id() }),
    queryParams: z.object({ ignoreFeedback: z.coerce.boolean().optional() }),
    pagination: "none",
    category: "dropbox",
    description: "Retrieve all submissions for a specific user in a dropbox folder.",
  }),
];

// --- Enrollment & Classlist, Auditing --------------------------------------------------------------

const enrollment: D2lRouteDescriptor[] = [
  route({
    operation: "le.classlist.list",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/classlist/",
    scope: "course",
    pathParams: noParams,
    pagination: "none",
    category: "enrollment",
    description: "Retrieve the enrolled users in the classlist for an org unit (unbounded — docs recommend the paged version instead).",
    curatedTools: ["get_classlist"],
  }),
  route({
    operation: "le.classlist.paged",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/classlist/paged/",
    scope: "course",
    pathParams: noParams,
    queryParams: z.object({
      onlyShowShownInGrades: z.coerce.boolean().optional(),
      searchTerm: z.string().optional(),
      roleId: id().optional(),
    }),
    pagination: "objectList",
    category: "enrollment",
    description: "Retrieve the enrolled users in the classlist for an org unit, paged; sorted by first name then last name then Identifier.",
  }),
  route({
    operation: "le.auditing.auditeeGet",
    product: "le",
    method: "GET",
    pathTemplate: "/auditing/auditees/{auditeeId}",
    scope: "global",
    pathParams: z.object({ auditeeId: id() }),
    pagination: "none",
    category: "auditing",
    description: "Retrieve information for an auditee, including the list of auditors monitoring that user.",
  }),
  route({
    operation: "le.auditing.auditorGet",
    product: "le",
    method: "GET",
    pathTemplate: "/auditing/auditors/{auditorId}",
    scope: "global",
    pathParams: z.object({ auditorId: id() }),
    pagination: "none",
    category: "auditing",
    description: "Retrieve information for an auditor, including the list of auditees being monitored.",
  }),
  route({
    operation: "le.auditing.auditeesForAuditor",
    product: "le",
    method: "GET",
    pathTemplate: "/auditing/auditors/{auditorId}/auditees/",
    scope: "global",
    pathParams: z.object({ auditorId: id() }),
    pagination: "none",
    category: "auditing",
    description: "Retrieve the list of users an auditor is auditing.",
  }),
];

// --- Grades & Grading --------------------------------------------------------------

const gradeValuesQuery = z.object({
  sort: z.string().optional(),
  pageSize: id().optional(),
  isGraded: z.coerce.boolean().optional(),
  searchText: z.string().optional(),
});

const grades: D2lRouteDescriptor[] = [
  route({
    operation: "le.grades.definitionsList",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/grades/",
    scope: "course",
    pathParams: noParams,
    pagination: "none",
    category: "grades",
    description: "Retrieve all the current grade objects for a particular org unit.",
    curatedTools: ["get_grades"],
  }),
  route({
    operation: "le.grades.definitionGet",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/grades/{gradeObjectId}",
    scope: "course",
    pathParams: z.object({ gradeObjectId: id() }),
    pagination: "none",
    category: "grades",
    description: "Retrieve a specific grade object for a particular org unit.",
  }),
  route({
    operation: "le.grades.definitionAccess",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/grades/{gradeObjectId}/access/",
    scope: "course",
    pathParams: z.object({ gradeObjectId: id() }),
    queryParams: userRoleQuery.merge(bookmarkQuery),
    pagination: "objectList",
    category: "grades",
    description: "Retrieve a list of users with access to a specified grade.",
  }),
  route({
    operation: "le.grades.exemptionsList",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/grades/{gradeObjectId}/exemptions/",
    scope: "course",
    pathParams: z.object({ gradeObjectId: id() }),
    pagination: "none",
    category: "grades",
    description: "Retrieve all the exempt users for a provided grade.",
  }),
  route({
    operation: "le.grades.exemptionGet",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/grades/{gradeObjectId}/exemptions/{userId}",
    scope: "course",
    pathParams: z.object({ gradeObjectId: id(), userId: id() }),
    pagination: "none",
    category: "grades",
    description: "Determine if a user is exempt from a grade.",
  }),
  route({
    operation: "le.grades.ipsis",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/grades/{gradeObjectId}/ipsis",
    scope: "course",
    pathParams: z.object({ gradeObjectId: id() }),
    pagination: "none",
    category: "grades",
    description: "Retrieve the IPSIS (SIS integration) details for a grade object.",
  }),
  route({
    operation: "le.grades.statistics",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/grades/{gradeObjectId}/statistics",
    scope: "course",
    pathParams: z.object({ gradeObjectId: id() }),
    pagination: "none",
    category: "grades",
    description: "Get statistics for a specified grade item.",
  }),
  route({
    operation: "le.grades.valuesForItem",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/grades/{gradeObjectId}/values/",
    scope: "course",
    pathParams: z.object({ gradeObjectId: id() }),
    queryParams: gradeValuesQuery,
    pagination: "objectList",
    category: "grades",
    description: "Retrieve each user's grade value for a particular grade object.",
  }),
  route({
    operation: "le.grades.valueForUser",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/grades/{gradeObjectId}/values/{userId}",
    scope: "course",
    pathParams: z.object({ gradeObjectId: id(), userId: id() }),
    pagination: "none",
    category: "grades",
    description: "Retrieve a specific grade value for a particular user assigned in an org unit.",
  }),
  route({
    operation: "le.grades.myValueForItem",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/grades/{gradeObjectId}/values/myGradeValue",
    scope: "course",
    pathParams: z.object({ gradeObjectId: id() }),
    pagination: "none",
    category: "grades",
    description: "Retrieve a specific grade value for the current user context assigned in a particular org unit.",
  }),
  route({
    operation: "le.grades.categoriesList",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/grades/categories/",
    scope: "course",
    pathParams: noParams,
    pagination: "none",
    category: "grades",
    description: "Retrieve a list of all grade categories for a provided org unit.",
  }),
  route({
    operation: "le.grades.categoryGet",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/grades/categories/{categoryId}",
    scope: "course",
    pathParams: z.object({ categoryId: id() }),
    pagination: "none",
    category: "grades",
    description: "Retrieve a specific grade category for a provided org unit.",
  }),
  route({
    operation: "le.grades.categoryIpsis",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/grades/categories/{categoryId}/ipsis",
    scope: "course",
    pathParams: z.object({ categoryId: id() }),
    pagination: "none",
    category: "grades",
    description: "Retrieve the IPSIS (SIS integration) details for a grade category.",
  }),
  route({
    operation: "le.grades.courseCompletionList",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/grades/courseCompletion/",
    scope: "course",
    pathParams: noParams,
    queryParams: z.object({ userId: id().optional(), startExpiry: z.string().optional(), endExpiry: z.string().optional() }).merge(bookmarkQuery),
    pagination: "bookmark",
    category: "grades",
    description: "Retrieve all the course completion records for an org unit.",
  }),
  route({
    operation: "le.grades.exemptionsForUser",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/grades/exemptions/{userId}",
    scope: "course",
    pathParams: z.object({ userId: id() }),
    pagination: "none",
    category: "grades",
    description: "Retrieve all the grade objects for a provided user in a provided org unit with exemption status included.",
  }),
  route({
    operation: "le.grades.finalValuesAll",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/grades/final/values/",
    scope: "course",
    pathParams: noParams,
    queryParams: gradeValuesQuery,
    pagination: "objectList",
    category: "grades",
    description: "Retrieve each user's final grade value for a particular org unit.",
    curatedTools: ["get_all_final_grades"],
  }),
  route({
    operation: "le.grades.finalValueForUser",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/grades/final/values/{userId}",
    scope: "course",
    pathParams: z.object({ userId: id() }),
    queryParams: z.object({ gradeType: z.string().optional() }),
    pagination: "none",
    category: "grades",
    description: "Retrieve the final grade value for a particular user.",
  }),
  route({
    operation: "le.grades.finalValueMy",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/grades/final/values/myGradeValue",
    scope: "course",
    pathParams: noParams,
    pagination: "none",
    category: "grades",
    description: "Retrieve the final grade value for the current user context.",
    curatedTools: ["get_my_final_grade"],
  }),
  route({
    operation: "le.grades.schemesList",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/grades/schemes/",
    scope: "course",
    pathParams: noParams,
    pagination: "none",
    category: "grades",
    description: "Retrieve all the grade schemes for a provided org unit.",
  }),
  route({
    operation: "le.grades.schemeGet",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/grades/schemes/{gradeSchemeId}",
    scope: "course",
    pathParams: z.object({ gradeSchemeId: id() }),
    pagination: "none",
    category: "grades",
    description: "Retrieve a particular grade scheme.",
  }),
  route({
    operation: "le.grades.schemeDefault",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/grades/schemes/default",
    scope: "course",
    pathParams: noParams,
    pagination: "none",
    category: "grades",
    description: "Retrieve the default grade scheme for a provided org unit.",
  }),
  route({
    operation: "le.grades.setup",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/grades/setup/",
    scope: "course",
    pathParams: noParams,
    pagination: "none",
    category: "grades",
    description: "Retrieve the grades configuration for the org unit.",
  }),
  route({
    operation: "le.grades.valuesAll",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/grades/values/",
    scope: "course",
    pathParams: noParams,
    queryParams: z.object({ gradeObjectTypeId: z.string().optional(), modifiedSince: z.string().optional(), pageSize: id().optional() }),
    pagination: "objectList",
    category: "grades",
    description: "Retrieve all grade values in bulk for every user in a particular org unit.",
    curatedTools: ["get_class_grades"],
  }),
  route({
    operation: "le.grades.valuesForUser",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/grades/values/{userId}/",
    scope: "course",
    pathParams: z.object({ userId: id() }),
    pagination: "none",
    category: "grades",
    description: "Retrieve all the grade values for a particular user assigned in an org unit.",
  }),
  route({
    operation: "le.grades.valuesDescendants",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/grades/values/descendants/",
    scope: "course",
    pathParams: noParams,
    queryParams: z.object({
      courseEndDate: z.string().optional(),
      courseStartDate: z.string().optional(),
      gradeObjectTypeId: z.string().optional(),
      includeInactiveCourses: z.coerce.boolean().optional(),
      modifiedSince: z.string().optional(),
      pageSize: id().optional(),
    }),
    pagination: "objectList",
    category: "grades",
    description: "Retrieve all grade values in bulk for every user in a group of org units (an org unit and its descendants).",
  }),
  route({
    operation: "le.grades.myValues",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/grades/values/myGradeValues/",
    scope: "course",
    pathParams: noParams,
    pagination: "none",
    category: "grades",
    description: "Retrieve all the grade values for the current user context assigned in a particular org unit.",
    curatedTools: ["get_grades"],
  }),
];

// --- Learning Outcomes (course-scoped) --------------------------------------------------------------

const learningOutcomes: D2lRouteDescriptor[] = [
  route({
    operation: "le.learningOutcomes.alignmentsList",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/lo/alignments/",
    scope: "course",
    pathParams: noParams,
    queryParams: z.object({ assessableOnly: z.coerce.boolean().optional() }),
    pagination: "none",
    category: "learning-outcomes",
    description: "Retrieve all the alignments in an org unit.",
  }),
  route({
    operation: "le.learningOutcomes.activityAlignments",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/lo/alignments/activity/{activityType}/{objectId}",
    scope: "course",
    pathParams: z.object({ activityType: z.string(), objectId: z.string() }),
    queryParams: z.object({ directOnly: z.coerce.boolean().optional() }),
    pagination: "none",
    category: "learning-outcomes",
    description: "Retrieve all the alignments to a given activity.",
  }),
  route({
    operation: "le.learningOutcomes.outcomeAlignments",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/lo/alignments/outcome/{outcomeId}",
    scope: "course",
    pathParams: z.object({ outcomeId: z.string() }),
    queryParams: z.object({ assessableOnly: z.coerce.boolean().optional() }),
    pagination: "none",
    category: "learning-outcomes",
    description: "Retrieve all the alignments to a given outcome in an org unit.",
  }),
  route({
    operation: "le.learningOutcomes.outcomeSetAlignments",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/lo/alignments/outcomeSet/{outcomeSetId}",
    scope: "course",
    pathParams: z.object({ outcomeSetId: id() }),
    queryParams: z.object({ assessableOnly: z.coerce.boolean().optional() }),
    pagination: "none",
    category: "learning-outcomes",
    description: "Retrieve all the alignments to outcomes in an outcome set in an org unit.",
  }),
  route({
    operation: "le.learningOutcomes.outcomeSetsList",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/lo/outcomeSets/",
    scope: "course",
    pathParams: noParams,
    pagination: "none",
    category: "learning-outcomes",
    description: "Retrieve all outcome sets in an org unit.",
  }),
  route({
    operation: "le.learningOutcomes.outcomeSetGet",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/lo/outcomeSets/{outcomeSetId}",
    scope: "course",
    pathParams: z.object({ outcomeSetId: id() }),
    pagination: "none",
    category: "learning-outcomes",
    description: "Retrieve a specific outcome set from an org unit.",
  }),
];

// --- News & Announcements --------------------------------------------------------------

const news: D2lRouteDescriptor[] = [
  route({
    operation: "le.news.list",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/news/",
    scope: "course",
    pathParams: noParams,
    queryParams: z.object({ since: z.string().optional() }),
    pagination: "none",
    category: "news",
    description: "Retrieve a list of news items for an org unit.",
    curatedTools: ["get_announcements"],
  }),
  route({
    operation: "le.news.get",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/news/{newsItemId}",
    scope: "course",
    pathParams: z.object({ newsItemId: id() }),
    pagination: "none",
    category: "news",
    description: "Retrieve a single news item for an org unit.",
  }),
  route({
    operation: "le.news.access",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/news/{newsItemId}/access/",
    scope: "course",
    pathParams: z.object({ newsItemId: id() }),
    queryParams: userRoleQuery,
    pagination: "objectList",
    category: "news",
    description: "Retrieve users with access to a specified news item.",
  }),
  route({
    operation: "le.news.attachment",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/news/{newsItemId}/attachments/{fileId}",
    scope: "course",
    pathParams: z.object({ newsItemId: id(), fileId: id() }),
    pagination: "binary",
    category: "news",
    description: "Download an attachment file for a news item.",
  }),
  route({
    operation: "le.news.sharing",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/news/{newsItemId}/sharing/",
    scope: "course",
    pathParams: z.object({ newsItemId: id() }),
    pagination: "objectList",
    category: "news",
    description: "Retrieve the org-unit sharing rules for a news item.",
  }),
  route({
    operation: "le.news.deletedList",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/news/deleted/",
    scope: "course",
    pathParams: noParams,
    queryParams: z.object({ global: z.coerce.boolean().optional() }),
    pagination: "none",
    category: "news",
    description: "Retrieve deleted news items for an org unit (includes hidden ones).",
  }),
  route({
    operation: "le.news.forUser",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/news/user/{userId}/",
    scope: "course",
    pathParams: z.object({ userId: id() }),
    pagination: "none",
    category: "news",
    description: "Retrieve news items from a specific org unit visible to a specific user. Subject to User Information Privacy permission controls.",
  }),
];

// --- Quizzes --------------------------------------------------------------

const quizzes: D2lRouteDescriptor[] = [
  route({
    operation: "le.quizzes.list",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/quizzes/",
    scope: "course",
    pathParams: noParams,
    pagination: "objectList",
    category: "quizzes",
    description: "List quizzes belonging to an org unit.",
    curatedTools: ["get_quizzes"],
  }),
  route({
    operation: "le.quizzes.get",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/quizzes/{quizId}",
    scope: "course",
    pathParams: z.object({ quizId: id() }),
    pagination: "none",
    category: "quizzes",
    description: "Retrieve a single quiz by ID.",
  }),
  route({
    operation: "le.quizzes.access",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/quizzes/{quizId}/access/",
    scope: "course",
    pathParams: z.object({ quizId: id() }),
    queryParams: userRoleQuery,
    pagination: "objectList",
    category: "quizzes",
    description: "Retrieve users with access to a specified quiz.",
  }),
  route({
    operation: "le.quizzes.attempts",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/quizzes/{quizId}/attempts/",
    scope: "course",
    pathParams: z.object({ quizId: id() }),
    queryParams: userIdOptionalQuery,
    pagination: "objectList",
    category: "quizzes",
    description: "Retrieve a list of attempts for a quiz.",
    curatedTools: ["get_quiz_attempts", "get_quiz_results"],
  }),
  route({
    operation: "le.quizzes.attemptGet",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/quizzes/{quizId}/attempts/{attemptId}",
    scope: "course",
    pathParams: z.object({ quizId: id(), attemptId: id() }),
    pagination: "none",
    category: "quizzes",
    description: "Retrieve a single quiz attempt.",
  }),
  route({
    operation: "le.quizzes.questions",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/quizzes/{quizId}/questions/",
    scope: "course",
    pathParams: z.object({ quizId: id() }),
    pagination: "objectList",
    category: "quizzes",
    description: "Retrieve all questions in a quiz.",
    curatedTools: ["get_quiz_questions"],
  }),
  route({
    operation: "le.quizzes.specialAccessList",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/quizzes/{quizId}/specialaccess/",
    scope: "course",
    pathParams: z.object({ quizId: id() }),
    pagination: "objectList",
    category: "quizzes",
    description: "Retrieve special access rules for users on a quiz.",
  }),
  route({
    operation: "le.quizzes.specialAccessGet",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/quizzes/{quizId}/specialaccess/{userId}",
    scope: "course",
    pathParams: z.object({ quizId: id(), userId: id() }),
    pagination: "none",
    category: "quizzes",
    description: "Retrieve one user's special access rule for a quiz.",
  }),
  route({
    operation: "le.quizzes.categoriesList",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/quizzes/categories/",
    scope: "course",
    pathParams: noParams,
    pagination: "objectList",
    category: "quizzes",
    description: "Retrieve quiz categories for an org unit.",
  }),
  route({
    operation: "le.quizzes.categoryGet",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/quizzes/categories/{categoryId}",
    scope: "course",
    pathParams: z.object({ categoryId: id() }),
    pagination: "none",
    category: "quizzes",
    description: "Retrieve a single quiz category.",
  }),
];

// --- Surveys --------------------------------------------------------------

const surveys: D2lRouteDescriptor[] = [
  route({
    operation: "le.surveys.list",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/surveys/",
    scope: "course",
    pathParams: noParams,
    pagination: "objectList",
    category: "surveys",
    description: "Retrieve all surveys for an org unit.",
    curatedTools: ["get_surveys"],
  }),
  route({
    operation: "le.surveys.get",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/surveys/{surveyId}",
    scope: "course",
    pathParams: z.object({ surveyId: id() }),
    pagination: "none",
    category: "surveys",
    description: "Retrieve a single survey.",
  }),
  route({
    operation: "le.surveys.access",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/surveys/{surveyId}/access/",
    scope: "course",
    pathParams: z.object({ surveyId: id() }),
    queryParams: userRoleQuery,
    pagination: "objectList",
    category: "surveys",
    description: "Retrieve users with access to a specified survey.",
  }),
  route({
    operation: "le.surveys.attempts",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/surveys/{surveyId}/attempts/",
    scope: "course",
    pathParams: z.object({ surveyId: id() }),
    queryParams: userIdOptionalQuery,
    pagination: "objectList",
    category: "surveys",
    description:
      "Retrieve a list of attempts for a survey. D2L returns 400 if userId is supplied on an anonymous survey (IsAnonymous=true), since anonymous attempts have no UserId to filter by.",
    curatedTools: ["get_survey_attempts", "get_survey_results"],
  }),
  route({
    operation: "le.surveys.attemptGet",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/surveys/{surveyId}/attempts/{attemptId}",
    scope: "course",
    pathParams: z.object({ surveyId: id(), attemptId: id() }),
    pagination: "none",
    category: "surveys",
    description: "Retrieve a single survey attempt.",
  }),
  route({
    operation: "le.surveys.questions",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/surveys/{surveyId}/questions/",
    scope: "course",
    pathParams: z.object({ surveyId: id() }),
    pagination: "objectList",
    category: "surveys",
    description: "Retrieve all questions in a survey (docs: identical structure to quiz questions).",
    curatedTools: ["get_survey_questions"],
  }),
  route({
    operation: "le.surveys.specialAccessList",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/surveys/{surveyId}/specialaccess/",
    scope: "course",
    pathParams: z.object({ surveyId: id() }),
    pagination: "objectList",
    category: "surveys",
    description: "Retrieve special access rules for a survey.",
  }),
  route({
    operation: "le.surveys.specialAccessGet",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/surveys/{surveyId}/specialaccess/{userId}",
    scope: "course",
    pathParams: z.object({ surveyId: id(), userId: id() }),
    pagination: "none",
    category: "surveys",
    description: "Retrieve one user's special access rule for a survey.",
  }),
  route({
    operation: "le.surveys.categoriesList",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/surveys/categories/",
    scope: "course",
    pathParams: noParams,
    pagination: "objectList",
    category: "surveys",
    description: "Retrieve survey categories for an org unit.",
  }),
  route({
    operation: "le.surveys.categoryGet",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/surveys/categories/{categoryId}",
    scope: "course",
    pathParams: z.object({ categoryId: id() }),
    pagination: "none",
    category: "surveys",
    description: "Retrieve a single survey category.",
  }),
];

// --- Course Overview --------------------------------------------------------------

const overview: D2lRouteDescriptor[] = [
  route({
    operation: "le.overview.get",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/overview",
    scope: "course",
    pathParams: noParams,
    pagination: "none",
    category: "overview",
    description: "Retrieve the content overview for a course offering.",
    curatedTools: ["get_course_overview"],
  }),
  route({
    operation: "le.overview.attachment",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/overview/attachment",
    scope: "course",
    pathParams: noParams,
    pagination: "binary",
    category: "overview",
    description: "Retrieve the content overview's file attachment for a course offering.",
  }),
];

// --- Accommodations --------------------------------------------------------------

const accommodations: D2lRouteDescriptor[] = [
  route({
    operation: "le.accommodations.forUser",
    product: "le",
    method: "GET",
    pathTemplate: "/accommodations/{orgUnitId}/users/{userId}",
    scope: "course",
    pathParams: z.object({ userId: id() }),
    pagination: "none",
    category: "accommodations",
    description: "Retrieve a specific user's accommodations profile in an org unit.",
  }),
  route({
    operation: "le.accommodations.my",
    product: "le",
    method: "GET",
    pathTemplate: "/accommodations/{orgUnitId}/myaccommodations",
    scope: "course",
    pathParams: noParams,
    pagination: "none",
    category: "accommodations",
    description: "Retrieve the calling user's own accommodations profile in an org unit.",
  }),
];

// --- Cross-Org Calendar --------------------------------------------------------------

const crossOrgCalendar: D2lRouteDescriptor[] = [
  route({
    operation: "le.calendar.global.itemCountsForUser",
    product: "le",
    method: "GET",
    pathTemplate: "/calendar/events/{userId}/itemCounts",
    scope: "user",
    pathParams: z.object({ userId: id() }),
    queryParams: z.object({
      association: z.string().optional(),
      eventType: z.string().optional(),
      orgUnitIdsCSV: z.string().optional(),
      startDateTime: z.string(),
      endDateTime: z.string(),
    }),
    pagination: "objectList",
    category: "cross-org-calendar",
    description: "Retrieve a count of a user's calendar events across their active enrolments (one EventCountInfo per org unit).",
  }),
  route({
    operation: "le.calendar.global.myEvents",
    product: "le",
    method: "GET",
    pathTemplate: "/calendar/events/myEvents/",
    scope: "user",
    pathParams: noParams,
    queryParams: orgUnitIdsCsvQuery({
      association: z.string().optional(),
      eventType: z.string().optional(),
      startDateTime: z.string(),
      endDateTime: z.string(),
    }),
    pagination: "objectList",
    category: "cross-org-calendar",
    description: "Retrieve the calling user's calendar events across a specified set of org units.",
    curatedTools: ["get_my_calendar_events"],
  }),
  route({
    operation: "le.calendar.global.myEventsItemCounts",
    product: "le",
    method: "GET",
    pathTemplate: "/calendar/events/myEvents/itemCounts/",
    scope: "user",
    pathParams: noParams,
    queryParams: orgUnitIdsCsvQuery({
      association: z.string().optional(),
      eventType: z.string().optional(),
      startDateTime: z.string().optional(),
      endDateTime: z.string().optional(),
    }),
    pagination: "objectList",
    category: "cross-org-calendar",
    description: "Retrieve a count of the calling user's calendar events across a specified set of org units.",
  }),
  route({
    operation: "le.calendar.global.myEventsWithOccurrences",
    product: "le",
    method: "GET",
    pathTemplate: "/calendar/events/myEventsWithOccurrences/",
    scope: "user",
    pathParams: noParams,
    queryParams: orgUnitIdsCsvQuery({
      association: z.string().optional(),
      eventType: z.string().optional(),
      startDateTime: z.string(),
      endDateTime: z.string(),
    }),
    pagination: "objectList",
    category: "cross-org-calendar",
    description: "Retrieve the calling user's calendar events, with their occurrences, across a specified set of org units.",
  }),
];

// --- Cross-Org Content --------------------------------------------------------------

const crossOrgContent: D2lRouteDescriptor[] = [
  route({
    operation: "le.content.global.completionsForUser",
    product: "le",
    method: "GET",
    pathTemplate: "/content/completions/{userId}/",
    scope: "user",
    pathParams: z.object({ userId: id() }),
    queryParams: orgUnitIdsCsvQuery({ ignoreInvalid: z.coerce.boolean().optional() }),
    pagination: "none",
    category: "cross-org-content",
    description: "Retrieve the count of completed and required content topics for a user, per org unit, across a supplied list of org units.",
  }),
  route({
    operation: "le.content.global.itemsForUser",
    product: "le",
    method: "GET",
    pathTemplate: "/content/items/{userId}",
    scope: "user",
    pathParams: z.object({ userId: id() }),
    queryParams: orgUnitIdsCsvQuery({
      completion: z.string().optional(),
      startDateTime: z.string().optional(),
      endDateTime: z.string().optional(),
      exemption: z.string().optional(),
    }),
    pagination: "objectList",
    category: "cross-org-content",
    description: "Retrieve the scheduled items for a particular user, within a number of org units.",
  }),
  route({
    operation: "le.content.global.myItems",
    product: "le",
    method: "GET",
    pathTemplate: "/content/myItems/",
    scope: "user",
    pathParams: noParams,
    queryParams: orgUnitIdsCsvQuery({
      completion: z.string().optional(),
      startDateTime: z.string().optional(),
      endDateTime: z.string().optional(),
    }),
    pagination: "objectList",
    category: "cross-org-content",
    description: "Retrieve the calling user's scheduled items.",
  }),
  route({
    operation: "le.content.global.myItemsCompletions",
    product: "le",
    method: "GET",
    pathTemplate: "/content/myItems/completions/",
    scope: "user",
    pathParams: noParams,
    queryParams: orgUnitIdsCsvQuery({ completedFromDateTime: z.string().optional(), completedToDateTime: z.string().optional() }),
    pagination: "objectList",
    category: "cross-org-content",
    description: "Retrieve the calling user's completed scheduled items.",
  }),
  route({
    operation: "le.content.global.myItemsCompletionsDue",
    product: "le",
    method: "GET",
    pathTemplate: "/content/myItems/completions/due/",
    scope: "user",
    pathParams: noParams,
    queryParams: orgUnitIdsCsvQuery({ completedFromDateTime: z.string().optional(), completedToDateTime: z.string().optional() }),
    pagination: "objectList",
    category: "cross-org-content",
    description: "Retrieve the calling user's completed scheduled items that have a due date. Exempted items don't appear.",
    curatedTools: ["get_due_items"],
  }),
  route({
    operation: "le.content.global.myItemsDue",
    product: "le",
    method: "GET",
    pathTemplate: "/content/myItems/due/",
    scope: "user",
    pathParams: noParams,
    queryParams: orgUnitIdsCsvQuery({
      completion: z.string().optional(),
      startDateTime: z.string().optional(),
      endDateTime: z.string().optional(),
    }),
    pagination: "objectList",
    category: "cross-org-content",
    description: "Retrieve the calling user's scheduled items still due, sorted by due date.",
  }),
  route({
    operation: "le.content.global.myItemsDueCounts",
    product: "le",
    method: "GET",
    pathTemplate: "/content/myItems/due/itemCounts/",
    scope: "user",
    pathParams: noParams,
    queryParams: orgUnitIdsCsvQuery({
      completion: z.string().optional(),
      startDateTime: z.string().optional(),
      endDateTime: z.string().optional(),
    }),
    pagination: "objectList",
    category: "cross-org-content",
    description: "Retrieve the quantities of the calling user's scheduled items still due.",
  }),
  route({
    operation: "le.content.global.myItemsCounts",
    product: "le",
    method: "GET",
    pathTemplate: "/content/myItems/itemCounts/",
    scope: "user",
    pathParams: noParams,
    queryParams: orgUnitIdsCsvQuery({
      completion: z.string().optional(),
      startDateTime: z.string().optional(),
      endDateTime: z.string().optional(),
    }),
    pagination: "objectList",
    category: "cross-org-content",
    description: "Retrieve the quantities of the calling user's scheduled items, organized by org unit.",
  }),
  route({
    operation: "le.content.global.overdueItemsAll",
    product: "le",
    method: "GET",
    pathTemplate: "/overdueItems/",
    scope: "global",
    pathParams: noParams,
    queryParams: z.object({ userId: id(), orgUnitIdsCSV: z.string().optional() }),
    pagination: "objectList",
    category: "cross-org-content",
    description:
      "Retrieve the overdue items for a particular user in a particular org unit. Org-wide/admin-scoped: self-access, auditor-of-auditee access, or instructor access to enrolled students in managed courses — broader than a plain course-instructor scope.",
  }),
  route({
    operation: "le.content.global.overdueItemsMy",
    product: "le",
    method: "GET",
    pathTemplate: "/overdueItems/myItems",
    scope: "user",
    pathParams: noParams,
    queryParams: z.object({ orgUnitIdsCSV: z.string().optional() }),
    pagination: "objectList",
    category: "cross-org-content",
    description: "Retrieve the calling user's overdue items, within a number of org units. Exempted items are considered not due.",
    curatedTools: ["get_overdue_items"],
  }),
];

// --- CPD --------------------------------------------------------------

const cpd: D2lRouteDescriptor[] = [
  route({
    operation: "le.cpd.categoryGet",
    product: "le",
    method: "GET",
    pathTemplate: "/cpd/category/{categoryId}",
    scope: "global",
    pathParams: z.object({ categoryId: id() }),
    pagination: "none",
    category: "cpd",
    description: "Retrieve a category.",
  }),
  route({
    operation: "le.cpd.methodGet",
    product: "le",
    method: "GET",
    pathTemplate: "/cpd/method/{methodId}",
    scope: "global",
    pathParams: z.object({ methodId: id() }),
    pagination: "none",
    category: "cpd",
    description: "Retrieve a method.",
  }),
  route({
    operation: "le.cpd.questionGet",
    product: "le",
    method: "GET",
    pathTemplate: "/cpd/question/{questionId}",
    scope: "global",
    pathParams: z.object({ questionId: id() }),
    pagination: "none",
    category: "cpd",
    description: "Retrieve a question.",
  }),
  route({
    operation: "le.cpd.recordGet",
    product: "le",
    method: "GET",
    pathTemplate: "/cpd/record/{recordId}",
    scope: "global",
    pathParams: z.object({ recordId: id() }),
    pagination: "none",
    category: "cpd",
    description: "Retrieve a CPD record.",
  }),
  route({
    operation: "le.cpd.recordAttachment",
    product: "le",
    method: "GET",
    pathTemplate: "/cpd/record/{recordId}/attachment/{attachmentId}",
    scope: "global",
    pathParams: z.object({ recordId: id(), attachmentId: id() }),
    pagination: "binary",
    category: "cpd",
    description: "Retrieve an attachment from a CPD record.",
  }),
  route({
    operation: "le.cpd.recordsForUser",
    product: "le",
    method: "GET",
    pathTemplate: "/cpd/record/user/{userId}",
    scope: "user",
    pathParams: z.object({ userId: id() }),
    queryParams: z.object({
      methodId: id().optional(),
      categoryId: id().optional(),
      recordName: z.string().optional(),
      startDate: z.string().optional(),
      endDate: z.string().optional(),
      recordStateId: z.string().optional(),
      sortDateAscending: z.coerce.boolean().optional(),
      limit: id().optional(),
      recordIdBookmark: id().optional(),
    }),
    pagination: "objectList",
    category: "cpd",
    description: "Retrieve a paged list of CPD records for a user. Likely elevated (manager/system-admin-level) permission when fetching another user's records.",
  }),
  route({
    operation: "le.cpd.targetProgressForUser",
    product: "le",
    method: "GET",
    pathTemplate: "/cpd/target/progress/user/{userId}",
    scope: "user",
    pathParams: z.object({ userId: id() }),
    queryParams: z.object({
      methodId: id().optional(),
      categoryId: id().optional(),
      recordName: z.string().optional(),
      startDate: z.string().optional(),
      endDate: z.string().optional(),
    }),
    pagination: "none",
    category: "cpd",
    description: "Retrieve a user's overall progress and their current progress for each category. 403s if the caller lacks permission to view this user's progress.",
  }),
];

// --- Cross-Org Dropbox --------------------------------------------------------------

const crossOrgDropbox: D2lRouteDescriptor[] = [
  route({
    operation: "le.dropbox.global.orgUnitsFeedback",
    product: "le",
    method: "GET",
    pathTemplate: "/dropbox/orgUnits/feedback/",
    scope: "global",
    pathParams: noParams,
    queryParams: z.object({ type: id().optional() }),
    pagination: "none",
    category: "cross-org-dropbox",
    description: "Retrieve the list of org units for which the current user has an assessment role on their dropbox folders (can see submissions and give feedback).",
  }),
];

// --- Cross-Org Grades --------------------------------------------------------------

const crossOrgGrades: D2lRouteDescriptor[] = [
  route({
    operation: "le.grades.global.courseCompletionForUser",
    product: "le",
    method: "GET",
    pathTemplate: "/grades/courseCompletion/{userId}/",
    scope: "user",
    pathParams: z.object({ userId: id() }),
    queryParams: z.object({ startExpiry: z.string().optional(), endExpiry: z.string().optional() }).merge(bookmarkQuery),
    pagination: "bookmark",
    category: "cross-org-grades",
    description: "Retrieve all the course completion records for a user, across org units.",
  }),
  route({
    operation: "le.grades.global.myFinalValues",
    product: "le",
    method: "GET",
    pathTemplate: "/grades/final/values/myGradeValues/",
    scope: "user",
    pathParams: noParams,
    queryParams: orgUnitIdsCsvQuery(),
    pagination: "objectList",
    category: "cross-org-grades",
    description: "Retrieve a list of final grade values for the current user context across a number of org units.",
  }),
  route({
    operation: "le.grades.global.valuesForUser",
    product: "le",
    method: "GET",
    pathTemplate: "/grades/values/{userId}",
    scope: "user",
    pathParams: z.object({ userId: id() }),
    queryParams: z.object({ modifiedSince: z.string().optional(), pageSize: id().optional() }),
    pagination: "objectList",
    category: "cross-org-grades",
    description: "Retrieve all the grade values in bulk for a particular user, across org units.",
  }),
];

// --- Course Imports & Copying, Course Copy Logs --------------------------------------------------------------

const imports: D2lRouteDescriptor[] = [
  route({
    operation: "le.import.copyStatus",
    product: "le",
    method: "GET",
    pathTemplate: "/import/{orgUnitId}/copy/{jobToken}",
    scope: "course",
    pathParams: z.object({ jobToken: z.string() }),
    pagination: "none",
    category: "imports",
    description: "Retrieve the status of a queued course copy job request.",
  }),
  route({
    operation: "le.import.importStatus",
    product: "le",
    method: "GET",
    pathTemplate: "/import/{orgUnitId}/imports/{jobToken}",
    scope: "course",
    pathParams: z.object({ jobToken: z.string() }),
    pagination: "none",
    category: "imports",
    description: "Retrieve the status of a queued course import job request.",
  }),
  route({
    operation: "le.import.importLogs",
    product: "le",
    method: "GET",
    // D2L's own docs literally spell this path param "orgUnitid" (lowercase id) — a
    // long-standing documentation typo, not a different parameter; still the same
    // auto-derived org unit id.
    pathTemplate: "/import/{orgUnitId}/imports/{jobToken}/logs/",
    scope: "course",
    pathParams: z.object({ jobToken: z.string() }),
    queryParams: bookmarkQuery,
    pagination: "bookmark",
    category: "imports",
    description: "Retrieve the logs for a course import job.",
  }),
  route({
    operation: "le.ccb.logs",
    product: "le",
    method: "GET",
    pathTemplate: "/ccb/logs",
    scope: "global",
    pathParams: noParams,
    queryParams: z
      .object({
        pageSize: id().optional(),
        sourceOrgUnitId: id().optional(),
        destinationOrgUnitId: id().optional(),
        subOrganizationOrgUnitId: id().optional(),
        startDate: z.string().optional(),
        endDate: z.string().optional(),
      })
      .merge(bookmarkQuery),
    // Corrected from "objectList": the declared bookmark query param means this is really
    // Api.PagedResultSet (PagingInfo/Items), consistent with every other bookmark-taking route
    // in this catalog — the initial research report's "objectListPage" classification for this
    // one route was internally inconsistent with its own documented bookmark param.
    pagination: "bookmark",
    category: "imports",
    description:
      "Retrieve logs for course-copy jobs, org-wide and filterable — distinct from le.import.importLogs, which is scoped to one specific job/org unit.",
  }),
];

// --- Cross-Org Learning Outcomes --------------------------------------------------------------

const crossOrgLearningOutcomes: D2lRouteDescriptor[] = [
  route({
    operation: "le.learningOutcomes.global.outcomeAlignments",
    product: "le",
    method: "GET",
    pathTemplate: "/lo/alignments/outcome/{outcomeId}",
    scope: "global",
    pathParams: z.object({ outcomeId: z.string() }),
    queryParams: z.object({ assessableOnly: z.coerce.boolean().optional(), activeOnly: z.coerce.boolean().optional() }),
    pagination: "none",
    category: "cross-org-learning-outcomes",
    description: "Retrieve the org units that contain alignments to a given outcome.",
  }),
  route({
    operation: "le.learningOutcomes.global.outcomeSetAlignments",
    product: "le",
    method: "GET",
    pathTemplate: "/lo/alignments/outcomeSet/{outcomeSetId}",
    scope: "global",
    pathParams: z.object({ outcomeSetId: id() }),
    queryParams: z.object({ assessableOnly: z.coerce.boolean().optional(), activeOnly: z.coerce.boolean().optional() }),
    pagination: "none",
    category: "cross-org-learning-outcomes",
    description: "Retrieve the org units that contain alignments to a given outcome set.",
  }),
  route({
    operation: "le.learningOutcomes.global.outcomeSetsList",
    product: "le",
    method: "GET",
    pathTemplate: "/lo/outcomeSets/",
    scope: "global",
    pathParams: noParams,
    pagination: "none",
    category: "cross-org-learning-outcomes",
    description: "Retrieve all organization-level outcome sets.",
  }),
  route({
    operation: "le.learningOutcomes.global.outcomeSetGet",
    product: "le",
    method: "GET",
    pathTemplate: "/lo/outcomeSets/{outcomeSetId}",
    scope: "global",
    pathParams: z.object({ outcomeSetId: id() }),
    pagination: "none",
    category: "cross-org-learning-outcomes",
    description: "Retrieve a specific organization-level outcome set.",
  }),
];

// --- Cross-Org News --------------------------------------------------------------

const crossOrgNews: D2lRouteDescriptor[] = [
  route({
    operation: "le.news.global.forUser",
    product: "le",
    method: "GET",
    pathTemplate: "/news/user/{userId}/",
    scope: "user",
    pathParams: z.object({ userId: id() }),
    queryParams: z.object({ since: z.string().optional(), until: z.string().optional() }),
    pagination: "objectList",
    category: "cross-org-news",
    description: "Retrieve news items for a specific user across the entire organization. Subject to User Information Privacy permission controls.",
  }),
];

// --- Updates & Activity --------------------------------------------------------------

const updates: D2lRouteDescriptor[] = [
  route({
    operation: "le.updates.myUpdates",
    product: "le",
    method: "GET",
    pathTemplate: "/{orgUnitId}/updates/myUpdates",
    scope: "course",
    pathParams: noParams,
    queryParams: z.object({ updateTypesCSV: z.string().optional() }),
    pagination: "none",
    category: "updates",
    description: "Retrieve counts of unread/pending updates for the current user, scoped to one org unit.",
  }),
  route({
    operation: "le.updates.global.myUpdates",
    product: "le",
    method: "GET",
    pathTemplate: "/updates/myUpdates/",
    scope: "user",
    pathParams: noParams,
    queryParams: orgUnitIdsCsvQuery({ updateTypesCSV: z.string().optional() }),
    pagination: "objectList",
    category: "updates",
    description: "Retrieve update counts for the current user across several org units in one call.",
    curatedTools: ["get_recent_updates"],
  }),
];

export const D2L_ROUTE_CATALOG: D2lRouteDescriptor[] = [
  ...assessmentRubrics,
  ...calendar,
  ...checklists,
  ...content,
  ...competencies,
  ...discussions,
  ...dropbox,
  ...enrollment,
  ...grades,
  ...learningOutcomes,
  ...news,
  ...quizzes,
  ...surveys,
  ...overview,
  ...accommodations,
  ...crossOrgCalendar,
  ...crossOrgContent,
  ...cpd,
  ...crossOrgDropbox,
  ...crossOrgGrades,
  ...imports,
  ...crossOrgLearningOutcomes,
  ...crossOrgNews,
  ...updates,
];

const catalogByOperation = new Map(D2L_ROUTE_CATALOG.map((r) => [r.operation, r]));

export function getRouteDescriptor(operation: string): D2lRouteDescriptor | undefined {
  return catalogByOperation.get(operation);
}
