import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { ToolContext } from "../types/tool-context.js";
import { registerCallD2lOperation } from "./call-d2l-operation.js";
import { registerGetAllFinalGrades } from "./get-all-final-grades.js";
import { registerGetAnnouncements } from "./get-announcements.js";
import { registerGetAssignmentFiles } from "./get-assignment-files.js";
import { registerGetAssignments } from "./get-assignments.js";
import { registerGetCalendarEvents } from "./get-calendar-events.js";
import { registerGetClassGrades } from "./get-class-grades.js";
import { registerGetClasslist } from "./get-classlist.js";
import { registerGetContentTopic } from "./get-content-topic.js";
import { registerGetCourseContent } from "./get-course-content.js";
import { registerGetCourseOverview } from "./get-course-overview.js";
import { registerGetDiscussionForums } from "./get-discussion-forums.js";
import { registerGetDiscussionPosts } from "./get-discussion-posts.js";
import { registerGetDiscussionTopics } from "./get-discussion-topics.js";
import { registerGetDropboxSubmissions } from "./get-dropbox-submissions.js";
import { registerGetDueItems } from "./get-due-items.js";
import { registerGetGrades } from "./get-grades.js";
import { registerGetGroups } from "./get-groups.js";
import { registerGetMyCalendarEvents } from "./get-my-calendar-events.js";
import { registerGetMyDropboxSubmission } from "./get-my-dropbox-submission.js";
import { registerGetMyFinalGrade } from "./get-my-final-grade.js";
import { registerGetOverdueItems } from "./get-overdue-items.js";
import { registerGetQuizAttempts } from "./get-quiz-attempts.js";
import { registerGetQuizQuestions } from "./get-quiz-questions.js";
import { registerGetQuizResults } from "./get-quiz-results.js";
import { registerGetQuizzes } from "./get-quizzes.js";
import { registerGetRecentUpdates } from "./get-recent-updates.js";
import { registerGetRubrics } from "./get-rubrics.js";
import { registerGetStepAnnouncements } from "./get-step-announcements.js";
import { registerGetStepCourseDetail } from "./get-step-course-detail.js";
import { registerGetStepTimetable } from "./get-step-timetable.js";
import { registerGetSurveyAttempts } from "./get-survey-attempts.js";
import { registerGetSurveyQuestions } from "./get-survey-questions.js";
import { registerGetSurveyResults } from "./get-survey-results.js";
import { registerGetSurveys } from "./get-surveys.js";
import { registerListCourses } from "./list-courses.js";
import { registerListD2lOperations } from "./list-d2l-operations.js";
import { registerListStepCourses } from "./list-step-courses.js";
import { registerSearchPolitemallCatalog } from "./search-politemall-catalog.js";
import { registerSearchStepCourses } from "./search-step-courses.js";
import { registerWhoami } from "./whoami.js";

// One file per tool. The same set is registered whether the server runs in the cloud or locally:
// tools only ever see a ToolContext, never where the caller's sessions are stored.
export function registerAllTools(server: McpServer, ctx: ToolContext): void {
  registerCallD2lOperation(server, ctx);
  registerGetAllFinalGrades(server, ctx);
  registerGetAnnouncements(server, ctx);
  registerGetAssignmentFiles(server, ctx);
  registerGetAssignments(server, ctx);
  registerGetCalendarEvents(server, ctx);
  registerGetClassGrades(server, ctx);
  registerGetClasslist(server, ctx);
  registerGetContentTopic(server, ctx);
  registerGetCourseContent(server, ctx);
  registerGetCourseOverview(server, ctx);
  registerGetDiscussionForums(server, ctx);
  registerGetDiscussionPosts(server, ctx);
  registerGetDiscussionTopics(server, ctx);
  registerGetDropboxSubmissions(server, ctx);
  registerGetDueItems(server, ctx);
  registerGetGrades(server, ctx);
  registerGetGroups(server, ctx);
  registerGetMyCalendarEvents(server, ctx);
  registerGetMyDropboxSubmission(server, ctx);
  registerGetMyFinalGrade(server, ctx);
  registerGetOverdueItems(server, ctx);
  registerGetQuizAttempts(server, ctx);
  registerGetQuizQuestions(server, ctx);
  registerGetQuizResults(server, ctx);
  registerGetQuizzes(server, ctx);
  registerGetRecentUpdates(server, ctx);
  registerGetRubrics(server, ctx);
  registerGetStepAnnouncements(server, ctx);
  registerGetStepCourseDetail(server, ctx);
  registerGetStepTimetable(server, ctx);
  registerGetSurveyAttempts(server, ctx);
  registerGetSurveyQuestions(server, ctx);
  registerGetSurveyResults(server, ctx);
  registerGetSurveys(server, ctx);
  registerListCourses(server, ctx);
  registerListD2lOperations(server, ctx);
  registerListStepCourses(server, ctx);
  registerSearchPolitemallCatalog(server, ctx);
  registerSearchStepCourses(server, ctx);
  registerWhoami(server, ctx);
}